# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: akudu/kudu/common/row_operations.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from akudu.kudu.util import pb_util_pb2 as akudu_dot_kudu_dot_util_dot_pb__util__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n&akudu/kudu/common/row_operations.proto\x12\x04kudu\x1a\x1d\x61kudu/kudu/util/pb_util.proto\"\xd3\x02\n\x0fRowOperationsPB\x12\x12\n\x04rows\x18\x02 \x01(\x0c\x42\x04\x88\xb5\x18\x01\x12\x1b\n\rindirect_data\x18\x03 \x01(\x0c\x42\x04\x88\xb5\x18\x01\"\x8e\x02\n\x04Type\x12\x0b\n\x07UNKNOWN\x10\x00\x12\n\n\x06INSERT\x10\x01\x12\n\n\x06UPDATE\x10\x02\x12\n\n\x06\x44\x45LETE\x10\x03\x12\n\n\x06UPSERT\x10\x05\x12\x11\n\rINSERT_IGNORE\x10\n\x12\x11\n\rUPDATE_IGNORE\x10\x0b\x12\x11\n\rDELETE_IGNORE\x10\x0c\x12\x11\n\rUPSERT_IGNORE\x10\r\x12\r\n\tSPLIT_ROW\x10\x04\x12\x15\n\x11RANGE_LOWER_BOUND\x10\x06\x12\x15\n\x11RANGE_UPPER_BOUND\x10\x07\x12\x1f\n\x1b\x45XCLUSIVE_RANGE_LOWER_BOUND\x10\x08\x12\x1f\n\x1bINCLUSIVE_RANGE_UPPER_BOUND\x10\tB\x11\n\x0forg.apache.kudu')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'akudu.kudu.common.row_operations_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'\n\017org.apache.kudu'
  _ROWOPERATIONSPB.fields_by_name['rows']._options = None
  _ROWOPERATIONSPB.fields_by_name['rows']._serialized_options = b'\210\265\030\001'
  _ROWOPERATIONSPB.fields_by_name['indirect_data']._options = None
  _ROWOPERATIONSPB.fields_by_name['indirect_data']._serialized_options = b'\210\265\030\001'
  _ROWOPERATIONSPB._serialized_start=80
  _ROWOPERATIONSPB._serialized_end=419
  _ROWOPERATIONSPB_TYPE._serialized_start=149
  _ROWOPERATIONSPB_TYPE._serialized_end=419
# @@protoc_insertion_point(module_scope)
