# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: akudu/kudu/util/proto_container_test2.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from akudu.kudu.util import proto_container_test_pb2 as akudu_dot_kudu_dot_util_dot_proto__container__test__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n+akudu/kudu/util/proto_container_test2.proto\x12\x04kudu\x1a*akudu/kudu/util/proto_container_test.proto\"C\n\x15ProtoContainerTest2PB\x12*\n\x06record\x18\x01 \x02(\x0b\x32\x1a.kudu.ProtoContainerTestPB')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'akudu.kudu.util.proto_container_test2_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _PROTOCONTAINERTEST2PB._serialized_start=97
  _PROTOCONTAINERTEST2PB._serialized_end=164
# @@protoc_insertion_point(module_scope)
