# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: kudu/transactions/transactions.proto

from google.protobuf.internal import enum_type_wrapper
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='kudu/transactions/transactions.proto',
  package='kudu.transactions',
  syntax='proto2',
  serialized_options=b'\n\034org.apache.kudu.transactions',
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n$kudu/transactions/transactions.proto\x12\x11kudu.transactions\"\xa4\x01\n\x10TxnStatusEntryPB\x12,\n\x05state\x18\x01 \x01(\x0e\x32\x1d.kudu.transactions.TxnStatePB\x12\x0c\n\x04user\x18\x02 \x01(\t\x12\x18\n\x10\x63ommit_timestamp\x18\x03 \x01(\x06\x12\x17\n\x0fstart_timestamp\x18\x04 \x01(\x03\x12!\n\x19last_transition_timestamp\x18\x05 \x01(\x03\"E\n\x15TxnParticipantEntryPB\x12,\n\x05state\x18\x01 \x01(\x0e\x32\x1d.kudu.transactions.TxnStatePB\"P\n\nTxnTokenPB\x12\x0e\n\x06txn_id\x18\x01 \x01(\x03\x12\x18\n\x10keepalive_millis\x18\x02 \x01(\r\x12\x18\n\x10\x65nable_keepalive\x18\x03 \x01(\x08*\x88\x01\n\nTxnStatePB\x12\x0b\n\x07UNKNOWN\x10\x00\x12\x08\n\x04OPEN\x10\x01\x12\x15\n\x11\x41\x42ORT_IN_PROGRESS\x10\x05\x12\x0b\n\x07\x41\x42ORTED\x10\x02\x12\x16\n\x12\x43OMMIT_IN_PROGRESS\x10\x03\x12\x18\n\x14\x46INALIZE_IN_PROGRESS\x10\x06\x12\r\n\tCOMMITTED\x10\x04\x42\x1e\n\x1corg.apache.kudu.transactions'
)

_TXNSTATEPB = _descriptor.EnumDescriptor(
  name='TxnStatePB',
  full_name='kudu.transactions.TxnStatePB',
  filename=None,
  file=DESCRIPTOR,
  create_key=_descriptor._internal_create_key,
  values=[
    _descriptor.EnumValueDescriptor(
      name='UNKNOWN', index=0, number=0,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='OPEN', index=1, number=1,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='ABORT_IN_PROGRESS', index=2, number=5,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='ABORTED', index=3, number=2,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='COMMIT_IN_PROGRESS', index=4, number=3,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='FINALIZE_IN_PROGRESS', index=5, number=6,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='COMMITTED', index=6, number=4,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=380,
  serialized_end=516,
)
_sym_db.RegisterEnumDescriptor(_TXNSTATEPB)

TxnStatePB = enum_type_wrapper.EnumTypeWrapper(_TXNSTATEPB)
UNKNOWN = 0
OPEN = 1
ABORT_IN_PROGRESS = 5
ABORTED = 2
COMMIT_IN_PROGRESS = 3
FINALIZE_IN_PROGRESS = 6
COMMITTED = 4



_TXNSTATUSENTRYPB = _descriptor.Descriptor(
  name='TxnStatusEntryPB',
  full_name='kudu.transactions.TxnStatusEntryPB',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='state', full_name='kudu.transactions.TxnStatusEntryPB.state', index=0,
      number=1, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='user', full_name='kudu.transactions.TxnStatusEntryPB.user', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='commit_timestamp', full_name='kudu.transactions.TxnStatusEntryPB.commit_timestamp', index=2,
      number=3, type=6, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='start_timestamp', full_name='kudu.transactions.TxnStatusEntryPB.start_timestamp', index=3,
      number=4, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='last_transition_timestamp', full_name='kudu.transactions.TxnStatusEntryPB.last_transition_timestamp', index=4,
      number=5, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=60,
  serialized_end=224,
)


_TXNPARTICIPANTENTRYPB = _descriptor.Descriptor(
  name='TxnParticipantEntryPB',
  full_name='kudu.transactions.TxnParticipantEntryPB',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='state', full_name='kudu.transactions.TxnParticipantEntryPB.state', index=0,
      number=1, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=226,
  serialized_end=295,
)


_TXNTOKENPB = _descriptor.Descriptor(
  name='TxnTokenPB',
  full_name='kudu.transactions.TxnTokenPB',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='txn_id', full_name='kudu.transactions.TxnTokenPB.txn_id', index=0,
      number=1, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='keepalive_millis', full_name='kudu.transactions.TxnTokenPB.keepalive_millis', index=1,
      number=2, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='enable_keepalive', full_name='kudu.transactions.TxnTokenPB.enable_keepalive', index=2,
      number=3, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=297,
  serialized_end=377,
)

_TXNSTATUSENTRYPB.fields_by_name['state'].enum_type = _TXNSTATEPB
_TXNPARTICIPANTENTRYPB.fields_by_name['state'].enum_type = _TXNSTATEPB
DESCRIPTOR.message_types_by_name['TxnStatusEntryPB'] = _TXNSTATUSENTRYPB
DESCRIPTOR.message_types_by_name['TxnParticipantEntryPB'] = _TXNPARTICIPANTENTRYPB
DESCRIPTOR.message_types_by_name['TxnTokenPB'] = _TXNTOKENPB
DESCRIPTOR.enum_types_by_name['TxnStatePB'] = _TXNSTATEPB
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

TxnStatusEntryPB = _reflection.GeneratedProtocolMessageType('TxnStatusEntryPB', (_message.Message,), {
  'DESCRIPTOR' : _TXNSTATUSENTRYPB,
  '__module__' : 'kudu.transactions.transactions_pb2'
  # @@protoc_insertion_point(class_scope:kudu.transactions.TxnStatusEntryPB)
  })
_sym_db.RegisterMessage(TxnStatusEntryPB)

TxnParticipantEntryPB = _reflection.GeneratedProtocolMessageType('TxnParticipantEntryPB', (_message.Message,), {
  'DESCRIPTOR' : _TXNPARTICIPANTENTRYPB,
  '__module__' : 'kudu.transactions.transactions_pb2'
  # @@protoc_insertion_point(class_scope:kudu.transactions.TxnParticipantEntryPB)
  })
_sym_db.RegisterMessage(TxnParticipantEntryPB)

TxnTokenPB = _reflection.GeneratedProtocolMessageType('TxnTokenPB', (_message.Message,), {
  'DESCRIPTOR' : _TXNTOKENPB,
  '__module__' : 'kudu.transactions.transactions_pb2'
  # @@protoc_insertion_point(class_scope:kudu.transactions.TxnTokenPB)
  })
_sym_db.RegisterMessage(TxnTokenPB)


DESCRIPTOR._options = None
# @@protoc_insertion_point(module_scope)
