# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: kudu/subprocess/subprocess.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import any_pb2 as google_dot_protobuf_dot_any__pb2
from kudu.common import wire_protocol_pb2 as kudu_dot_common_dot_wire__protocol__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='kudu/subprocess/subprocess.proto',
  package='kudu.subprocess',
  syntax='proto2',
  serialized_options=b'\n\032org.apache.kudu.subprocess',
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n kudu/subprocess/subprocess.proto\x12\x0fkudu.subprocess\x1a\x19google/protobuf/any.proto\x1a\x1fkudu/common/wire_protocol.proto\"/\n\rEchoRequestPB\x12\x0c\n\x04\x64\x61ta\x18\x01 \x02(\t\x12\x10\n\x08sleep_ms\x18\x02 \x01(\x05\"\x1e\n\x0e\x45\x63hoResponsePB\x12\x0c\n\x04\x64\x61ta\x18\x01 \x02(\t\"\xac\x01\n\x13SubprocessMetricsPB\x12\x1d\n\x15inbound_queue_time_ms\x18\x01 \x01(\x03\x12\x1e\n\x16outbound_queue_time_ms\x18\x02 \x01(\x03\x12\x1c\n\x14inbound_queue_length\x18\x03 \x01(\x03\x12\x1d\n\x15outbound_queue_length\x18\x04 \x01(\x03\x12\x19\n\x11\x65xecution_time_ms\x18\x05 \x01(\x03\"H\n\x13SubprocessRequestPB\x12\n\n\x02id\x18\x01 \x01(\x03\x12%\n\x07request\x18\x03 \x01(\x0b\x32\x14.google.protobuf.Any\"\xa3\x01\n\x14SubprocessResponsePB\x12\n\n\x02id\x18\x01 \x01(\x03\x12 \n\x05\x65rror\x18\x02 \x01(\x0b\x32\x11.kudu.AppStatusPB\x12&\n\x08response\x18\x03 \x01(\x0b\x32\x14.google.protobuf.Any\x12\x35\n\x07metrics\x18\x04 \x01(\x0b\x32$.kudu.subprocess.SubprocessMetricsPBB\x1c\n\x1aorg.apache.kudu.subprocess'
  ,
  dependencies=[google_dot_protobuf_dot_any__pb2.DESCRIPTOR,kudu_dot_common_dot_wire__protocol__pb2.DESCRIPTOR,])




_ECHOREQUESTPB = _descriptor.Descriptor(
  name='EchoRequestPB',
  full_name='kudu.subprocess.EchoRequestPB',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='data', full_name='kudu.subprocess.EchoRequestPB.data', index=0,
      number=1, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='sleep_ms', full_name='kudu.subprocess.EchoRequestPB.sleep_ms', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=113,
  serialized_end=160,
)


_ECHORESPONSEPB = _descriptor.Descriptor(
  name='EchoResponsePB',
  full_name='kudu.subprocess.EchoResponsePB',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='data', full_name='kudu.subprocess.EchoResponsePB.data', index=0,
      number=1, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=162,
  serialized_end=192,
)


_SUBPROCESSMETRICSPB = _descriptor.Descriptor(
  name='SubprocessMetricsPB',
  full_name='kudu.subprocess.SubprocessMetricsPB',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='inbound_queue_time_ms', full_name='kudu.subprocess.SubprocessMetricsPB.inbound_queue_time_ms', index=0,
      number=1, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='outbound_queue_time_ms', full_name='kudu.subprocess.SubprocessMetricsPB.outbound_queue_time_ms', index=1,
      number=2, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='inbound_queue_length', full_name='kudu.subprocess.SubprocessMetricsPB.inbound_queue_length', index=2,
      number=3, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='outbound_queue_length', full_name='kudu.subprocess.SubprocessMetricsPB.outbound_queue_length', index=3,
      number=4, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='execution_time_ms', full_name='kudu.subprocess.SubprocessMetricsPB.execution_time_ms', index=4,
      number=5, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=195,
  serialized_end=367,
)


_SUBPROCESSREQUESTPB = _descriptor.Descriptor(
  name='SubprocessRequestPB',
  full_name='kudu.subprocess.SubprocessRequestPB',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='id', full_name='kudu.subprocess.SubprocessRequestPB.id', index=0,
      number=1, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='request', full_name='kudu.subprocess.SubprocessRequestPB.request', index=1,
      number=3, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=369,
  serialized_end=441,
)


_SUBPROCESSRESPONSEPB = _descriptor.Descriptor(
  name='SubprocessResponsePB',
  full_name='kudu.subprocess.SubprocessResponsePB',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='id', full_name='kudu.subprocess.SubprocessResponsePB.id', index=0,
      number=1, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='error', full_name='kudu.subprocess.SubprocessResponsePB.error', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='response', full_name='kudu.subprocess.SubprocessResponsePB.response', index=2,
      number=3, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='metrics', full_name='kudu.subprocess.SubprocessResponsePB.metrics', index=3,
      number=4, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=444,
  serialized_end=607,
)

_SUBPROCESSREQUESTPB.fields_by_name['request'].message_type = google_dot_protobuf_dot_any__pb2._ANY
_SUBPROCESSRESPONSEPB.fields_by_name['error'].message_type = kudu_dot_common_dot_wire__protocol__pb2._APPSTATUSPB
_SUBPROCESSRESPONSEPB.fields_by_name['response'].message_type = google_dot_protobuf_dot_any__pb2._ANY
_SUBPROCESSRESPONSEPB.fields_by_name['metrics'].message_type = _SUBPROCESSMETRICSPB
DESCRIPTOR.message_types_by_name['EchoRequestPB'] = _ECHOREQUESTPB
DESCRIPTOR.message_types_by_name['EchoResponsePB'] = _ECHORESPONSEPB
DESCRIPTOR.message_types_by_name['SubprocessMetricsPB'] = _SUBPROCESSMETRICSPB
DESCRIPTOR.message_types_by_name['SubprocessRequestPB'] = _SUBPROCESSREQUESTPB
DESCRIPTOR.message_types_by_name['SubprocessResponsePB'] = _SUBPROCESSRESPONSEPB
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

EchoRequestPB = _reflection.GeneratedProtocolMessageType('EchoRequestPB', (_message.Message,), {
  'DESCRIPTOR' : _ECHOREQUESTPB,
  '__module__' : 'kudu.subprocess.subprocess_pb2'
  # @@protoc_insertion_point(class_scope:kudu.subprocess.EchoRequestPB)
  })
_sym_db.RegisterMessage(EchoRequestPB)

EchoResponsePB = _reflection.GeneratedProtocolMessageType('EchoResponsePB', (_message.Message,), {
  'DESCRIPTOR' : _ECHORESPONSEPB,
  '__module__' : 'kudu.subprocess.subprocess_pb2'
  # @@protoc_insertion_point(class_scope:kudu.subprocess.EchoResponsePB)
  })
_sym_db.RegisterMessage(EchoResponsePB)

SubprocessMetricsPB = _reflection.GeneratedProtocolMessageType('SubprocessMetricsPB', (_message.Message,), {
  'DESCRIPTOR' : _SUBPROCESSMETRICSPB,
  '__module__' : 'kudu.subprocess.subprocess_pb2'
  # @@protoc_insertion_point(class_scope:kudu.subprocess.SubprocessMetricsPB)
  })
_sym_db.RegisterMessage(SubprocessMetricsPB)

SubprocessRequestPB = _reflection.GeneratedProtocolMessageType('SubprocessRequestPB', (_message.Message,), {
  'DESCRIPTOR' : _SUBPROCESSREQUESTPB,
  '__module__' : 'kudu.subprocess.subprocess_pb2'
  # @@protoc_insertion_point(class_scope:kudu.subprocess.SubprocessRequestPB)
  })
_sym_db.RegisterMessage(SubprocessRequestPB)

SubprocessResponsePB = _reflection.GeneratedProtocolMessageType('SubprocessResponsePB', (_message.Message,), {
  'DESCRIPTOR' : _SUBPROCESSRESPONSEPB,
  '__module__' : 'kudu.subprocess.subprocess_pb2'
  # @@protoc_insertion_point(class_scope:kudu.subprocess.SubprocessResponsePB)
  })
_sym_db.RegisterMessage(SubprocessResponsePB)


DESCRIPTOR._options = None
# @@protoc_insertion_point(module_scope)
