# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: akudu/kudu/ranger/ranger.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1e\x61kudu/kudu/ranger/ranger.proto\x12\x0bkudu.ranger\"\x9c\x01\n\x0fRangerRequestPB\x12\x10\n\x08\x64\x61tabase\x18\x01 \x01(\t\x12\r\n\x05table\x18\x02 \x01(\t\x12\x0e\n\x06\x63olumn\x18\x03 \x01(\t\x12%\n\x06\x61\x63tion\x18\x04 \x01(\x0e\x32\x15.kudu.ranger.ActionPB\x12\x1f\n\x17requires_delegate_admin\x18\x05 \x01(\x08\x12\x10\n\x08is_owner\x18\x06 \x01(\x08\"#\n\x10RangerResponsePB\x12\x0f\n\x07\x61llowed\x18\x01 \x01(\x08\"2\n\x16RangerControlRequestPB\x12\x18\n\x10refresh_policies\x18\x01 \x01(\x08\"9\n\x17RangerControlResponsePB\x12\x0f\n\x07success\x18\x01 \x01(\x08\x12\r\n\x05\x65rror\x18\x02 \x01(\t\"\x91\x01\n\x13RangerRequestListPB\x12.\n\x08requests\x18\x01 \x03(\x0b\x32\x1c.kudu.ranger.RangerRequestPB\x12\x0c\n\x04user\x18\x02 \x01(\t\x12<\n\x0f\x63ontrol_request\x18\x03 \x01(\x0b\x32#.kudu.ranger.RangerControlRequestPB\"\x88\x01\n\x14RangerResponseListPB\x12\x30\n\tresponses\x18\x01 \x03(\x0b\x32\x1d.kudu.ranger.RangerResponsePB\x12>\n\x10\x63ontrol_response\x18\x02 \x01(\x0b\x32$.kudu.ranger.RangerControlResponsePB*r\n\x08\x41\x63tionPB\x12\n\n\x06SELECT\x10\x00\x12\n\n\x06INSERT\x10\x01\x12\n\n\x06UPDATE\x10\x02\x12\n\n\x06\x44\x45LETE\x10\x03\x12\t\n\x05\x41LTER\x10\x04\x12\n\n\x06\x43REATE\x10\x05\x12\x08\n\x04\x44ROP\x10\x06\x12\x07\n\x03\x41LL\x10\x07\x12\x0c\n\x08METADATA\x10\x08\x42\x18\n\x16org.apache.kudu.ranger')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'akudu.kudu.ranger.ranger_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'\n\026org.apache.kudu.ranger'
  _ACTIONPB._serialized_start=641
  _ACTIONPB._serialized_end=755
  _RANGERREQUESTPB._serialized_start=48
  _RANGERREQUESTPB._serialized_end=204
  _RANGERRESPONSEPB._serialized_start=206
  _RANGERRESPONSEPB._serialized_end=241
  _RANGERCONTROLREQUESTPB._serialized_start=243
  _RANGERCONTROLREQUESTPB._serialized_end=293
  _RANGERCONTROLRESPONSEPB._serialized_start=295
  _RANGERCONTROLRESPONSEPB._serialized_end=352
  _RANGERREQUESTLISTPB._serialized_start=355
  _RANGERREQUESTLISTPB._serialized_end=500
  _RANGERRESPONSELISTPB._serialized_start=503
  _RANGERRESPONSELISTPB._serialized_end=639
# @@protoc_insertion_point(module_scope)
