# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: kudu/ranger/ranger.proto

from google.protobuf.internal import enum_type_wrapper
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='kudu/ranger/ranger.proto',
  package='kudu.ranger',
  syntax='proto2',
  serialized_options=b'\n\026org.apache.kudu.ranger',
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x18kudu/ranger/ranger.proto\x12\x0bkudu.ranger\"\x9c\x01\n\x0fRangerRequestPB\x12\x10\n\x08\x64\x61tabase\x18\x01 \x01(\t\x12\r\n\x05table\x18\x02 \x01(\t\x12\x0e\n\x06\x63olumn\x18\x03 \x01(\t\x12%\n\x06\x61\x63tion\x18\x04 \x01(\x0e\x32\x15.kudu.ranger.ActionPB\x12\x1f\n\x17requires_delegate_admin\x18\x05 \x01(\x08\x12\x10\n\x08is_owner\x18\x06 \x01(\x08\"#\n\x10RangerResponsePB\x12\x0f\n\x07\x61llowed\x18\x01 \x01(\x08\"2\n\x16RangerControlRequestPB\x12\x18\n\x10refresh_policies\x18\x01 \x01(\x08\"9\n\x17RangerControlResponsePB\x12\x0f\n\x07success\x18\x01 \x01(\x08\x12\r\n\x05\x65rror\x18\x02 \x01(\t\"\x91\x01\n\x13RangerRequestListPB\x12.\n\x08requests\x18\x01 \x03(\x0b\x32\x1c.kudu.ranger.RangerRequestPB\x12\x0c\n\x04user\x18\x02 \x01(\t\x12<\n\x0f\x63ontrol_request\x18\x03 \x01(\x0b\x32#.kudu.ranger.RangerControlRequestPB\"\x88\x01\n\x14RangerResponseListPB\x12\x30\n\tresponses\x18\x01 \x03(\x0b\x32\x1d.kudu.ranger.RangerResponsePB\x12>\n\x10\x63ontrol_response\x18\x02 \x01(\x0b\x32$.kudu.ranger.RangerControlResponsePB*r\n\x08\x41\x63tionPB\x12\n\n\x06SELECT\x10\x00\x12\n\n\x06INSERT\x10\x01\x12\n\n\x06UPDATE\x10\x02\x12\n\n\x06\x44\x45LETE\x10\x03\x12\t\n\x05\x41LTER\x10\x04\x12\n\n\x06\x43REATE\x10\x05\x12\x08\n\x04\x44ROP\x10\x06\x12\x07\n\x03\x41LL\x10\x07\x12\x0c\n\x08METADATA\x10\x08\x42\x18\n\x16org.apache.kudu.ranger'
)

_ACTIONPB = _descriptor.EnumDescriptor(
  name='ActionPB',
  full_name='kudu.ranger.ActionPB',
  filename=None,
  file=DESCRIPTOR,
  create_key=_descriptor._internal_create_key,
  values=[
    _descriptor.EnumValueDescriptor(
      name='SELECT', index=0, number=0,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='INSERT', index=1, number=1,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='UPDATE', index=2, number=2,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='DELETE', index=3, number=3,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='ALTER', index=4, number=4,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='CREATE', index=5, number=5,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='DROP', index=6, number=6,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='ALL', index=7, number=7,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='METADATA', index=8, number=8,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=635,
  serialized_end=749,
)
_sym_db.RegisterEnumDescriptor(_ACTIONPB)

ActionPB = enum_type_wrapper.EnumTypeWrapper(_ACTIONPB)
SELECT = 0
INSERT = 1
UPDATE = 2
DELETE = 3
ALTER = 4
CREATE = 5
DROP = 6
ALL = 7
METADATA = 8



_RANGERREQUESTPB = _descriptor.Descriptor(
  name='RangerRequestPB',
  full_name='kudu.ranger.RangerRequestPB',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='database', full_name='kudu.ranger.RangerRequestPB.database', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='table', full_name='kudu.ranger.RangerRequestPB.table', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='column', full_name='kudu.ranger.RangerRequestPB.column', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='action', full_name='kudu.ranger.RangerRequestPB.action', index=3,
      number=4, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='requires_delegate_admin', full_name='kudu.ranger.RangerRequestPB.requires_delegate_admin', index=4,
      number=5, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='is_owner', full_name='kudu.ranger.RangerRequestPB.is_owner', index=5,
      number=6, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=42,
  serialized_end=198,
)


_RANGERRESPONSEPB = _descriptor.Descriptor(
  name='RangerResponsePB',
  full_name='kudu.ranger.RangerResponsePB',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='allowed', full_name='kudu.ranger.RangerResponsePB.allowed', index=0,
      number=1, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=200,
  serialized_end=235,
)


_RANGERCONTROLREQUESTPB = _descriptor.Descriptor(
  name='RangerControlRequestPB',
  full_name='kudu.ranger.RangerControlRequestPB',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='refresh_policies', full_name='kudu.ranger.RangerControlRequestPB.refresh_policies', index=0,
      number=1, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=237,
  serialized_end=287,
)


_RANGERCONTROLRESPONSEPB = _descriptor.Descriptor(
  name='RangerControlResponsePB',
  full_name='kudu.ranger.RangerControlResponsePB',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='success', full_name='kudu.ranger.RangerControlResponsePB.success', index=0,
      number=1, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='error', full_name='kudu.ranger.RangerControlResponsePB.error', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=289,
  serialized_end=346,
)


_RANGERREQUESTLISTPB = _descriptor.Descriptor(
  name='RangerRequestListPB',
  full_name='kudu.ranger.RangerRequestListPB',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='requests', full_name='kudu.ranger.RangerRequestListPB.requests', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='user', full_name='kudu.ranger.RangerRequestListPB.user', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='control_request', full_name='kudu.ranger.RangerRequestListPB.control_request', index=2,
      number=3, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=349,
  serialized_end=494,
)


_RANGERRESPONSELISTPB = _descriptor.Descriptor(
  name='RangerResponseListPB',
  full_name='kudu.ranger.RangerResponseListPB',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='responses', full_name='kudu.ranger.RangerResponseListPB.responses', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='control_response', full_name='kudu.ranger.RangerResponseListPB.control_response', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=497,
  serialized_end=633,
)

_RANGERREQUESTPB.fields_by_name['action'].enum_type = _ACTIONPB
_RANGERREQUESTLISTPB.fields_by_name['requests'].message_type = _RANGERREQUESTPB
_RANGERREQUESTLISTPB.fields_by_name['control_request'].message_type = _RANGERCONTROLREQUESTPB
_RANGERRESPONSELISTPB.fields_by_name['responses'].message_type = _RANGERRESPONSEPB
_RANGERRESPONSELISTPB.fields_by_name['control_response'].message_type = _RANGERCONTROLRESPONSEPB
DESCRIPTOR.message_types_by_name['RangerRequestPB'] = _RANGERREQUESTPB
DESCRIPTOR.message_types_by_name['RangerResponsePB'] = _RANGERRESPONSEPB
DESCRIPTOR.message_types_by_name['RangerControlRequestPB'] = _RANGERCONTROLREQUESTPB
DESCRIPTOR.message_types_by_name['RangerControlResponsePB'] = _RANGERCONTROLRESPONSEPB
DESCRIPTOR.message_types_by_name['RangerRequestListPB'] = _RANGERREQUESTLISTPB
DESCRIPTOR.message_types_by_name['RangerResponseListPB'] = _RANGERRESPONSELISTPB
DESCRIPTOR.enum_types_by_name['ActionPB'] = _ACTIONPB
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

RangerRequestPB = _reflection.GeneratedProtocolMessageType('RangerRequestPB', (_message.Message,), {
  'DESCRIPTOR' : _RANGERREQUESTPB,
  '__module__' : 'kudu.ranger.ranger_pb2'
  # @@protoc_insertion_point(class_scope:kudu.ranger.RangerRequestPB)
  })
_sym_db.RegisterMessage(RangerRequestPB)

RangerResponsePB = _reflection.GeneratedProtocolMessageType('RangerResponsePB', (_message.Message,), {
  'DESCRIPTOR' : _RANGERRESPONSEPB,
  '__module__' : 'kudu.ranger.ranger_pb2'
  # @@protoc_insertion_point(class_scope:kudu.ranger.RangerResponsePB)
  })
_sym_db.RegisterMessage(RangerResponsePB)

RangerControlRequestPB = _reflection.GeneratedProtocolMessageType('RangerControlRequestPB', (_message.Message,), {
  'DESCRIPTOR' : _RANGERCONTROLREQUESTPB,
  '__module__' : 'kudu.ranger.ranger_pb2'
  # @@protoc_insertion_point(class_scope:kudu.ranger.RangerControlRequestPB)
  })
_sym_db.RegisterMessage(RangerControlRequestPB)

RangerControlResponsePB = _reflection.GeneratedProtocolMessageType('RangerControlResponsePB', (_message.Message,), {
  'DESCRIPTOR' : _RANGERCONTROLRESPONSEPB,
  '__module__' : 'kudu.ranger.ranger_pb2'
  # @@protoc_insertion_point(class_scope:kudu.ranger.RangerControlResponsePB)
  })
_sym_db.RegisterMessage(RangerControlResponsePB)

RangerRequestListPB = _reflection.GeneratedProtocolMessageType('RangerRequestListPB', (_message.Message,), {
  'DESCRIPTOR' : _RANGERREQUESTLISTPB,
  '__module__' : 'kudu.ranger.ranger_pb2'
  # @@protoc_insertion_point(class_scope:kudu.ranger.RangerRequestListPB)
  })
_sym_db.RegisterMessage(RangerRequestListPB)

RangerResponseListPB = _reflection.GeneratedProtocolMessageType('RangerResponseListPB', (_message.Message,), {
  'DESCRIPTOR' : _RANGERRESPONSELISTPB,
  '__module__' : 'kudu.ranger.ranger_pb2'
  # @@protoc_insertion_point(class_scope:kudu.ranger.RangerResponseListPB)
  })
_sym_db.RegisterMessage(RangerResponseListPB)


DESCRIPTOR._options = None
# @@protoc_insertion_point(module_scope)
