# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: kudu/util/histogram.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='kudu/util/histogram.proto',
  package='kudu',
  syntax='proto2',
  serialized_options=b'\n\017org.apache.kudu',
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x19kudu/util/histogram.proto\x12\x04kudu\"\x90\x03\n\x13HistogramSnapshotPB\x12\x0c\n\x04type\x18\x01 \x02(\t\x12\x0c\n\x04name\x18\x02 \x02(\t\x12\x13\n\x0b\x64\x65scription\x18\x03 \x01(\t\x12\x0c\n\x04unit\x18\x04 \x02(\t\x12\r\n\x05label\x18\x13 \x01(\t\x12\x1b\n\x13max_trackable_value\x18\x05 \x02(\x04\x12\x1e\n\x16num_significant_digits\x18\x06 \x02(\x05\x12\x13\n\x0btotal_count\x18\x07 \x02(\x04\x12\x11\n\ttotal_sum\x18\x12 \x01(\x04\x12\x0b\n\x03min\x18\x08 \x02(\x04\x12\x0c\n\x04mean\x18\t \x02(\x01\x12\x15\n\rpercentile_75\x18\n \x02(\x04\x12\x15\n\rpercentile_95\x18\x0b \x02(\x04\x12\x15\n\rpercentile_99\x18\x0c \x02(\x04\x12\x17\n\x0fpercentile_99_9\x18\r \x02(\x04\x12\x18\n\x10percentile_99_99\x18\x0e \x02(\x04\x12\x0b\n\x03max\x18\x0f \x02(\x04\x12\x12\n\x06values\x18\x10 \x03(\x04\x42\x02\x10\x01\x12\x12\n\x06\x63ounts\x18\x11 \x03(\x04\x42\x02\x10\x01\"I\n\x18HistogramSnapshotsListPB\x12-\n\nhistograms\x18\x01 \x03(\x0b\x32\x19.kudu.HistogramSnapshotPBB\x11\n\x0forg.apache.kudu'
)




_HISTOGRAMSNAPSHOTPB = _descriptor.Descriptor(
  name='HistogramSnapshotPB',
  full_name='kudu.HistogramSnapshotPB',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='type', full_name='kudu.HistogramSnapshotPB.type', index=0,
      number=1, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='name', full_name='kudu.HistogramSnapshotPB.name', index=1,
      number=2, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='description', full_name='kudu.HistogramSnapshotPB.description', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='unit', full_name='kudu.HistogramSnapshotPB.unit', index=3,
      number=4, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='label', full_name='kudu.HistogramSnapshotPB.label', index=4,
      number=19, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='max_trackable_value', full_name='kudu.HistogramSnapshotPB.max_trackable_value', index=5,
      number=5, type=4, cpp_type=4, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='num_significant_digits', full_name='kudu.HistogramSnapshotPB.num_significant_digits', index=6,
      number=6, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='total_count', full_name='kudu.HistogramSnapshotPB.total_count', index=7,
      number=7, type=4, cpp_type=4, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='total_sum', full_name='kudu.HistogramSnapshotPB.total_sum', index=8,
      number=18, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='min', full_name='kudu.HistogramSnapshotPB.min', index=9,
      number=8, type=4, cpp_type=4, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='mean', full_name='kudu.HistogramSnapshotPB.mean', index=10,
      number=9, type=1, cpp_type=5, label=2,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='percentile_75', full_name='kudu.HistogramSnapshotPB.percentile_75', index=11,
      number=10, type=4, cpp_type=4, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='percentile_95', full_name='kudu.HistogramSnapshotPB.percentile_95', index=12,
      number=11, type=4, cpp_type=4, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='percentile_99', full_name='kudu.HistogramSnapshotPB.percentile_99', index=13,
      number=12, type=4, cpp_type=4, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='percentile_99_9', full_name='kudu.HistogramSnapshotPB.percentile_99_9', index=14,
      number=13, type=4, cpp_type=4, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='percentile_99_99', full_name='kudu.HistogramSnapshotPB.percentile_99_99', index=15,
      number=14, type=4, cpp_type=4, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='max', full_name='kudu.HistogramSnapshotPB.max', index=16,
      number=15, type=4, cpp_type=4, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='values', full_name='kudu.HistogramSnapshotPB.values', index=17,
      number=16, type=4, cpp_type=4, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=b'\020\001', file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='counts', full_name='kudu.HistogramSnapshotPB.counts', index=18,
      number=17, type=4, cpp_type=4, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=b'\020\001', file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=36,
  serialized_end=436,
)


_HISTOGRAMSNAPSHOTSLISTPB = _descriptor.Descriptor(
  name='HistogramSnapshotsListPB',
  full_name='kudu.HistogramSnapshotsListPB',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='histograms', full_name='kudu.HistogramSnapshotsListPB.histograms', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=438,
  serialized_end=511,
)

_HISTOGRAMSNAPSHOTSLISTPB.fields_by_name['histograms'].message_type = _HISTOGRAMSNAPSHOTPB
DESCRIPTOR.message_types_by_name['HistogramSnapshotPB'] = _HISTOGRAMSNAPSHOTPB
DESCRIPTOR.message_types_by_name['HistogramSnapshotsListPB'] = _HISTOGRAMSNAPSHOTSLISTPB
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

HistogramSnapshotPB = _reflection.GeneratedProtocolMessageType('HistogramSnapshotPB', (_message.Message,), {
  'DESCRIPTOR' : _HISTOGRAMSNAPSHOTPB,
  '__module__' : 'kudu.util.histogram_pb2'
  # @@protoc_insertion_point(class_scope:kudu.HistogramSnapshotPB)
  })
_sym_db.RegisterMessage(HistogramSnapshotPB)

HistogramSnapshotsListPB = _reflection.GeneratedProtocolMessageType('HistogramSnapshotsListPB', (_message.Message,), {
  'DESCRIPTOR' : _HISTOGRAMSNAPSHOTSLISTPB,
  '__module__' : 'kudu.util.histogram_pb2'
  # @@protoc_insertion_point(class_scope:kudu.HistogramSnapshotsListPB)
  })
_sym_db.RegisterMessage(HistogramSnapshotsListPB)


DESCRIPTOR._options = None
_HISTOGRAMSNAPSHOTPB.fields_by_name['values']._options = None
_HISTOGRAMSNAPSHOTPB.fields_by_name['counts']._options = None
# @@protoc_insertion_point(module_scope)
