# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: kudu/util/proto_container_test2.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from kudu.util import proto_container_test_pb2 as kudu_dot_util_dot_proto__container__test__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='kudu/util/proto_container_test2.proto',
  package='kudu',
  syntax='proto2',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n%kudu/util/proto_container_test2.proto\x12\x04kudu\x1a$kudu/util/proto_container_test.proto\"C\n\x15ProtoContainerTest2PB\x12*\n\x06record\x18\x01 \x02(\x0b\x32\x1a.kudu.ProtoContainerTestPB'
  ,
  dependencies=[kudu_dot_util_dot_proto__container__test__pb2.DESCRIPTOR,])




_PROTOCONTAINERTEST2PB = _descriptor.Descriptor(
  name='ProtoContainerTest2PB',
  full_name='kudu.ProtoContainerTest2PB',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='record', full_name='kudu.ProtoContainerTest2PB.record', index=0,
      number=1, type=11, cpp_type=10, label=2,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=85,
  serialized_end=152,
)

_PROTOCONTAINERTEST2PB.fields_by_name['record'].message_type = kudu_dot_util_dot_proto__container__test__pb2._PROTOCONTAINERTESTPB
DESCRIPTOR.message_types_by_name['ProtoContainerTest2PB'] = _PROTOCONTAINERTEST2PB
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

ProtoContainerTest2PB = _reflection.GeneratedProtocolMessageType('ProtoContainerTest2PB', (_message.Message,), {
  'DESCRIPTOR' : _PROTOCONTAINERTEST2PB,
  '__module__' : 'kudu.util.proto_container_test2_pb2'
  # @@protoc_insertion_point(class_scope:kudu.ProtoContainerTest2PB)
  })
_sym_db.RegisterMessage(ProtoContainerTest2PB)


# @@protoc_insertion_point(module_scope)
