# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: kudu/util/version_info.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='kudu/util/version_info.proto',
  package='kudu',
  syntax='proto2',
  serialized_options=b'\n\017org.apache.kudu',
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x1ckudu/util/version_info.proto\x12\x04kudu\"\xc2\x01\n\rVersionInfoPB\x12\x10\n\x08git_hash\x18\x01 \x01(\t\x12\x16\n\x0e\x62uild_hostname\x18\x02 \x01(\t\x12\x17\n\x0f\x62uild_timestamp\x18\x03 \x01(\t\x12\x16\n\x0e\x62uild_username\x18\x04 \x01(\t\x12\x18\n\x10\x62uild_clean_repo\x18\x05 \x01(\x08\x12\x10\n\x08\x62uild_id\x18\x06 \x01(\t\x12\x12\n\nbuild_type\x18\x07 \x01(\t\x12\x16\n\x0eversion_string\x18\x08 \x01(\tB\x11\n\x0forg.apache.kudu'
)




_VERSIONINFOPB = _descriptor.Descriptor(
  name='VersionInfoPB',
  full_name='kudu.VersionInfoPB',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='git_hash', full_name='kudu.VersionInfoPB.git_hash', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='build_hostname', full_name='kudu.VersionInfoPB.build_hostname', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='build_timestamp', full_name='kudu.VersionInfoPB.build_timestamp', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='build_username', full_name='kudu.VersionInfoPB.build_username', index=3,
      number=4, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='build_clean_repo', full_name='kudu.VersionInfoPB.build_clean_repo', index=4,
      number=5, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='build_id', full_name='kudu.VersionInfoPB.build_id', index=5,
      number=6, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='build_type', full_name='kudu.VersionInfoPB.build_type', index=6,
      number=7, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='version_string', full_name='kudu.VersionInfoPB.version_string', index=7,
      number=8, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=39,
  serialized_end=233,
)

DESCRIPTOR.message_types_by_name['VersionInfoPB'] = _VERSIONINFOPB
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

VersionInfoPB = _reflection.GeneratedProtocolMessageType('VersionInfoPB', (_message.Message,), {
  'DESCRIPTOR' : _VERSIONINFOPB,
  '__module__' : 'kudu.util.version_info_pb2'
  # @@protoc_insertion_point(class_scope:kudu.VersionInfoPB)
  })
_sym_db.RegisterMessage(VersionInfoPB)


DESCRIPTOR._options = None
# @@protoc_insertion_point(module_scope)
