# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: akudu/kudu/consensus/opid.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1f\x61kudu/kudu/consensus/opid.proto\x12\x0ekudu.consensus\"#\n\x04OpId\x12\x0c\n\x04term\x18\x01 \x02(\x03\x12\r\n\x05index\x18\x02 \x02(\x03\x42\x1b\n\x19org.apache.kudu.consensus')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'akudu.kudu.consensus.opid_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'\n\031org.apache.kudu.consensus'
  _OPID._serialized_start=51
  _OPID._serialized_end=86
# @@protoc_insertion_point(module_scope)
